{% set name = "onnxruntime-extensions" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/onnxruntime-extensions/archive/v{{ version }}.tar.gz
  sha256: 2c91d81b098865d0d37debea1e9a37d35de418f05b83642f95498002853bbab2

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - ninja
    - python
    - setuptools
    - wheel
    - numpy
    - pip
    - libabseil # [osx]
  host:
    - python
    - setuptools
    - wheel
    - numpy
    - pip
  run:
    - python
    - onnxruntime

test:
  imports:
    - onnxruntime_extensions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/onnxruntime-extensions
  license: Apache-2.0 AND MIT
  summary: "onnxruntime-extensions: A specialized pre- and post- processing library for ONNX Runtime"
  license_file:
    - LICENSE
    - cmake/externals/farmhash/COPYING
    - cmake/externals/opencv/LICENSE
    - cmake/externals/opencv/COPYRIGHT
    - nuget/LICENSE.txt

extra:
  recipe-maintainers:
    - Chizkiyahu
